name: camera1_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  esys_flutter_share: ^1.0.2
  image_picker: ^0.6.7+12
  gallery_saver: ^2.0.1
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable: ^0.6.0
  animated_floatactionbuttons: ^0.1.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: BungeeShade
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf
